-- MySQL Script generated by MySQL Workbench
-- Sun Apr 21 22:43:59 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Usuário`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Usuário` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Usuário` (
  `idUser` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CadastroCliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`CadastroCliente` ;

CREATE TABLE IF NOT EXISTS `mydb`.`CadastroCliente` (
  `idCliente` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `Sobrenome` VARCHAR(45) NOT NULL,
  `Apelido` VARCHAR(45) NOT NULL,
  `Telefone` VARCHAR(45) NOT NULL,
  `Data de Cadastro` DATE GENERATED ALWAYS AS () VIRTUAL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CadastroTreino`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`CadastroTreino` ;

CREATE TABLE IF NOT EXISTS `mydb`.`CadastroTreino` (
  `idCadastroTreino` INT NOT NULL,
  `idCliente` INT NOT NULL COMMENT 'REFERENCES cadastro_clientes(idCliente)',
  `Data` DATE NOT NULL,
  `Inicio` DECIMAL NOT NULL,
  `Duração` DECIMAL NOT NULL,
  `Valor do Treino` DECIMAL ZEROFILL NOT NULL,
  PRIMARY KEY (`idCadastroTreino`),
  CONSTRAINT `idCliente`
    FOREIGN KEY (`idCliente`)
    REFERENCES `mydb`.`CadastroCliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `idCliente_idx` ON `mydb`.`CadastroTreino` (`idCliente` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
